baseURL = "https://www.eyousefi.com/"
languageCode = "en-us"
title = "eyousefi"
theme = "archie"
copyright = "© Erfan Yousefi | Opinions are my own"
pygmentsstyle = "monokai"
pygmentsCodeFences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	featherIconsCDN=true
	subtitle = "All persons fictitious, including the author"
canonifyurls = true
paginate = 3
summaryLength = 30
enableEmoji = true
googleAnalytics = "UA-60175069-1" #Google Analytics ID
[author]
    name = "Erfan"       #Author name
    linkedin = "ErfanYousefi"   #LinkedIn username
    twitter = "2Erfan"    #Twitter username

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ErfanY"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/2Erfan"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/ErfanYousefi"
